window.WordData = {
  // 입문: 2~3글자 일상 단어
  beginner: [
    { korean: '사과', english: 'Apple' },
    { korean: '바나나', english: 'Banana' },
    { korean: '물', english: 'Water' },
    { korean: '밥', english: 'Rice' },
    { korean: '집', english: 'House' },
    { korean: '책', english: 'Book' },
    { korean: '달', english: 'Moon' },
    { korean: '별', english: 'Star' },
    { korean: '불', english: 'Fire' },
    { korean: '눈', english: 'Snow / Eye' },
    { korean: '비', english: 'Rain' },
    { korean: '바람', english: 'Wind' },
    { korean: '하늘', english: 'Sky' },
    { korean: '바다', english: 'Sea' },
    { korean: '산', english: 'Mountain' },
    { korean: '강', english: 'River' },
    { korean: '나무', english: 'Tree' },
    { korean: '꽃', english: 'Flower' },
    { korean: '손', english: 'Hand' },
    { korean: '발', english: 'Foot' },
    { korean: '코', english: 'Nose' },
    { korean: '입', english: 'Mouth' },
    { korean: '귀', english: 'Ear' },
    { korean: '머리', english: 'Head' },
    { korean: '빵', english: 'Bread' },
    { korean: '우유', english: 'Milk' },
    { korean: '고기', english: 'Meat' },
    { korean: '국', english: 'Soup' },
    { korean: '차', english: 'Tea / Car' },
    { korean: '학교', english: 'School' },
  ],

  // 중급: 사자성어 (4자 한자어)
  intermediate: [
    { korean: '일석이조', english: 'Kill two birds with one stone', hint: '一石二鳥' },
    { korean: '오리무중', english: 'In a complete fog / Mystery', hint: '五里霧中' },
    { korean: '동문서답', english: 'Irrelevant answer', hint: '東問西答' },
    { korean: '사면초가', english: 'Surrounded on all sides', hint: '四面楚歌' },
    { korean: '이심전심', english: 'Telepathy / Meeting of minds', hint: '以心傳心' },
    { korean: '유비무환', english: 'Preparedness prevents disaster', hint: '有備無患' },
    { korean: '청출어람', english: 'The student surpasses the teacher', hint: '靑出於藍' },
    { korean: '우공이산', english: 'Persistence overcomes everything', hint: '愚公移山' },
    { korean: '형설지공', english: 'Hard-won success through hardship', hint: '螢雪之功' },
    { korean: '마이동풍', english: 'Turning a deaf ear', hint: '馬耳東風' },
    { korean: '자업자득', english: 'You reap what you sow', hint: '自業自得' },
    { korean: '과유불급', english: 'Too much is as bad as too little', hint: '過猶不及' },
    { korean: '견물생심', english: 'Seeing is wanting', hint: '見物生心' },
    { korean: '금상첨화', english: 'Icing on the cake', hint: '錦上添花' },
    { korean: '낙천지명', english: 'Accept fate with joy', hint: '樂天知命' },
    { korean: '노심초사', english: 'Worry and anxiety', hint: '勞心焦思' },
    { korean: '다다익선', english: 'The more the better', hint: '多多益善' },
    { korean: '막역지우', english: 'Bosom friend', hint: '莫逆之友' },
    { korean: '배은망덕', english: 'Ingratitude', hint: '背恩忘德' },
    { korean: '산전수전', english: 'Experienced everything', hint: '山戰水戰' },
    { korean: '설상가상', english: 'Adding insult to injury', hint: '雪上加霜' },
    { korean: '아전인수', english: 'Self-serving interpretation', hint: '我田引水' },
    { korean: '어부지리', english: 'Third party benefits', hint: '漁父之利' },
    { korean: '전화위복', english: 'Turn misfortune into blessing', hint: '轉禍爲福' },
    { korean: '죽마고우', english: 'Childhood friend', hint: '竹馬故友' },
    { korean: '천고마비', english: 'Clear autumn sky', hint: '天高馬肥' },
    { korean: '칠전팔기', english: 'Never give up', hint: '七顚八起' },
    { korean: '함흥차사', english: 'No news at all', hint: '咸興差使' },
    { korean: '호연지기', english: 'Magnanimous spirit', hint: '浩然之氣' },
    { korean: '횡설수설', english: 'Talking nonsense', hint: '橫說竪說' },
  ],

  // 고급: 빈칸에 알맞은 단어 (속담)
  advanced: [
    { korean: '하늘이 ___ 별 따기', english: 'As hard as picking stars from the sky', answer: '맞닿은', hint: 'Extremely difficult task' },
    { korean: '가는 말이 고와야 ___ 말이 곱다', english: 'As you sow, so shall you reap', answer: '오는', hint: 'Treat others as you wish to be treated' },
    { korean: '급할수록 ___', english: 'The more hurry, the less speed', answer: '돌아가라', hint: 'Slow down when in a rush' },
    { korean: '백지장도 ___ 들면 낫다', english: 'Two heads are better than one', answer: '맞들면', hint: 'Cooperation is better' },
    { korean: '구슬이 서 말이라도 ___ 야 보배', english: 'A gem is not polished without rubbing', answer: '꿰어야', hint: 'Things are only useful when put together' },
    { korean: '윗물이 맑아야 ___ 물이 맑다', english: 'Leaders must set a good example', answer: '아랫물', hint: 'Top affects the bottom' },
    { korean: '세 살 버릇 ___ 간다', english: 'Old habits die hard', answer: '여든까지', hint: 'Habits formed early last long' },
    { korean: '티끌 모아 ___', english: 'Every little bit helps', answer: '태산', hint: 'Small things accumulate' },
    { korean: '낮말은 새가 듣고 밤말은 ___ 듣는다', english: 'Walls have ears', answer: '쥐가', hint: 'Be careful what you say' },
    { korean: '소 잃고 ___ 고친다', english: 'Lock the stable after the horse has bolted', answer: '외양간', hint: 'Too late to fix' },
    { korean: '고생 끝에 ___ 온다', english: 'After hardship comes happiness', answer: '낙', hint: 'Good follows bad' },
    { korean: '원숭이도 ___ 에서 떨어진다', english: 'Even experts make mistakes', answer: '나무', hint: 'Nobody is perfect' },
    { korean: '발 없는 말이 ___ 리 간다', english: 'Words travel fast', answer: '천', hint: 'Rumors spread quickly' },
    { korean: '공든 탑이 ___ 랴', english: 'Hard work never fails', answer: '무너지', hint: 'Effort is rewarded' },
    { korean: '가재는 ___ 편', english: 'Birds of a feather flock together', answer: '게', hint: 'Similar sides together' },
    { korean: '호랑이도 제 말 하면 ___', english: 'Speak of the devil', answer: '온다', hint: 'The person appears when mentioned' },
    { korean: '남의 떡이 ___ 커 보인다', english: 'The grass is greener on the other side', answer: '더', hint: 'Others seem better off' },
    { korean: '돌다리도 두들겨 보고 ___', english: 'Look before you leap', answer: '건너라', hint: 'Be careful even when safe' },
    { korean: '배보다 ___ 이 더 크다', english: 'The cure is worse than the disease', answer: '배꼽', hint: 'Side effect bigger than main' },
    { korean: '웃는 ___ 에 침 못 뱉는다', english: 'You cannot be angry at a smiling face', answer: '얼굴', hint: 'A smile disarms anger' },
    { korean: '찬물도 ___ 이 있다', english: 'Everything has its proper time', answer: '위아래', hint: 'Order matters' },
    { korean: '콩 심은 데 콩 나고 ___ 심은 데 팥 난다', english: 'You reap what you sow', answer: '팥', hint: 'Cause and effect' },
    { korean: '하룻강아지 ___ 무서운 줄 모른다', english: 'Fools rush in where angels fear to tread', answer: '범', hint: 'Inexperience leads to recklessness' },
    { korean: '될성부른 나무는 ___ 부터 알아본다', english: 'A good tree is known from its fruit', answer: '떡잎', hint: 'Early signs tell the future' },
    { korean: '아니 땐 굴뚝에 ___ 나랴', english: 'Where there is smoke, there is fire', answer: '연기', hint: 'No effect without cause' },
    { korean: '천 리 길도 ___ 부터', english: 'A journey of a thousand miles begins with a single step', answer: '한 걸음', hint: 'Start small' },
    { korean: '모로 가도 ___ 만 가면 된다', english: 'The end justifies the means', answer: '서울', hint: 'Destination matters' },
    { korean: '벼는 익을수록 ___ 숙인다', english: 'The more one knows, the more humble one is', answer: '고개를', hint: 'Wisdom brings humility' },
    { korean: '지렁이도 ___ 이 있다', english: 'Even a worm will turn', answer: '밟으면', hint: 'Everyone has limits' },
    { korean: '평안감사도 ___ 하면 그만', english: 'You can lead a horse to water', answer: '싫으면', hint: 'Cannot force someone' },
  ],

  // 특급: 다의어와 유의어
  expert: [
    { korean: '눈 (目)', english: 'Eye', synonym: '시선, 눈길', usage: '눈이 크다 (big eyes)' },
    { korean: '눈 (雪)', english: 'Snow', synonym: '설', usage: '눈이 오다 (it snows)' },
    { korean: '배 (腹)', english: 'Stomach/Belly', synonym: '복부', usage: '배가 고프다 (hungry)' },
    { korean: '배 (船)', english: 'Ship/Boat', synonym: '선박', usage: '배를 타다 (ride a boat)' },
    { korean: '배 (梨)', english: 'Pear', synonym: '배나무 열매', usage: '배를 먹다 (eat a pear)' },
    { korean: '말 (言)', english: 'Word/Speech', synonym: '언어, 언급', usage: '말을 하다 (to speak)' },
    { korean: '말 (馬)', english: 'Horse', synonym: '마필', usage: '말을 타다 (ride a horse)' },
    { korean: '차 (車)', english: 'Car', synonym: '자동차', usage: '차를 운전하다 (drive a car)' },
    { korean: '차 (茶)', english: 'Tea', synonym: '음료', usage: '차를 마시다 (drink tea)' },
    { korean: '밝다', english: 'Bright', synonym: '환하다, 명랑하다', usage: '방이 밝다 (bright room)' },
    { korean: '작다', english: 'Small', synonym: '소형, 미소', usage: '크기가 작다 (small size)' },
    { korean: '크다', english: 'Big/Large', synonym: '대형, 거대하다', usage: '집이 크다 (big house)' },
    { korean: '빠르다', english: 'Fast', synonym: '신속하다, 재빠르다', usage: '달리기가 빠르다 (fast runner)' },
    { korean: '느리다', english: 'Slow', synonym: '완만하다, 더디다', usage: '걸음이 느리다 (slow walker)' },
    { korean: '예쁘다', english: 'Pretty', synonym: '아름답다, 귀엽다', usage: '꽃이 예쁘다 (pretty flower)' },
    { korean: '기쁘다', english: 'Happy/Joyful', synonym: '즐겁다, 행복하다', usage: '마음이 기쁘다 (joyful heart)' },
    { korean: '슬프다', english: 'Sad', synonym: '우울하다, 서글프다', usage: '마음이 슬프다 (sad heart)' },
    { korean: '무섭다', english: 'Scary', synonym: '두렵다, 공포스럽다', usage: '귀신이 무섭다 (scary ghost)' },
    { korean: '힘들다', english: 'Hard/Difficult', synonym: '어렵다, 고되다', usage: '일이 힘들다 (hard work)' },
    { korean: '쉽다', english: 'Easy', synonym: '간단하다, 수월하다', usage: '문제가 쉽다 (easy problem)' },
    { korean: '높다', english: 'High/Tall', synonym: '거대하다, 우뚝하다', usage: '산이 높다 (tall mountain)' },
    { korean: '낮다', english: 'Low', synonym: '평평하다', usage: '천장이 낮다 (low ceiling)' },
    { korean: '많다', english: 'Many/Much', synonym: '풍부하다, 다양하다', usage: '사람이 많다 (many people)' },
    { korean: '적다', english: 'Few/Little', synonym: '부족하다, 드물다', usage: '시간이 적다 (little time)' },
    { korean: '좋다', english: 'Good', synonym: '훌륭하다, 멋있다', usage: '날씨가 좋다 (good weather)' },
    { korean: '나쁘다', english: 'Bad', synonym: '안 좋다, 불량하다', usage: '날씨가 나쁘다 (bad weather)' },
    { korean: '덥다', english: 'Hot', synonym: '뜨겁다, 후덥지근하다', usage: '날씨가 덥다 (hot weather)' },
    { korean: '춥다', english: 'Cold', synonym: '차갑다, 싸늘하다', usage: '날씨가 춥다 (cold weather)' },
    { korean: '맛있다', english: 'Delicious', synonym: '맛나다, 훌륭하다', usage: '음식이 맛있다 (delicious food)' },
    { korean: '맛없다', english: 'Tasteless', synonym: '밍밍하다', usage: '음식이 맛없다 (bad food)' },
  ],

  // 초특급: 낱말퍼즐
  master: [
    { clue: 'Korean traditional clothing', answer: '한복', hint: '한국의 전통 의상' },
    { clue: 'Korean fermented vegetable dish', answer: '김치', hint: '한국의 대표 음식' },
    { clue: 'Korean martial art', answer: '태권도', hint: '한국의 무술' },
    { clue: 'Korean writing system', answer: '한글', hint: '한국의 문자' },
    { clue: 'Korean traditional music', answer: '국악', hint: '한국의 전통 음악' },
    { clue: 'Korean traditional house', answer: '한옥', hint: '한국의 전통 가옥' },
    { clue: 'Korean rice wine', answer: '막걸리', hint: '한국의 전통 술' },
    { clue: 'Korean BBQ meat', answer: '불고기', hint: '한국의 대표 고기 요리' },
    { clue: 'Korean mixed rice bowl', answer: '비빔밥', hint: '여러 재료를 섞은 밥' },
    { clue: 'Korean spicy rice cake', answer: '떡볶이', hint: '매운 떡 요리' },
    { clue: 'Korean seaweed soup', answer: '미역국', hint: '생일에 먹는 국' },
    { clue: 'Korean cold noodles', answer: '냉면', hint: '차가운 국수 요리' },
    { clue: 'Korean dumpling', answer: '만두', hint: '속을 채운 반죽 요리' },
    { clue: 'Korean pancake', answer: '전', hint: '기름에 부친 음식' },
    { clue: 'Korean soybean paste stew', answer: '된장찌개', hint: '된장으로 끓인 찌개' },
    { clue: 'Korean spicy stew', answer: '김치찌개', hint: '김치로 끓인 찌개' },
    { clue: 'Korean street food skewer', answer: '꼬치', hint: '꼬챙이에 꽂은 음식' },
    { clue: 'Korean traditional market', answer: '전통시장', hint: '옛날 방식의 시장' },
    { clue: 'Korean independence movement day', answer: '삼일절', hint: '3월 1일 기념일' },
    { clue: 'Korean alphabet day', answer: '한글날', hint: '10월 9일 기념일' },
    { clue: 'Korean New Year', answer: '설날', hint: '음력 1월 1일' },
    { clue: 'Korean autumn harvest festival', answer: '추석', hint: '음력 8월 15일' },
    { clue: 'Korean traditional fan dance', answer: '부채춤', hint: '부채를 들고 추는 춤' },
    { clue: 'Korean royal palace in Seoul', answer: '경복궁', hint: '서울의 대표 궁궐' },
    { clue: 'Korean folk village', answer: '민속촌', hint: '전통 생활을 보여주는 곳' },
    { clue: 'Korean traditional boat', answer: '황포돛배', hint: '돛을 단 전통 배' },
    { clue: 'Korean traditional hat', answer: '갓', hint: '선비가 쓰던 모자' },
    { clue: 'Korean traditional storage jar', answer: '항아리', hint: '음식을 저장하는 그릇' },
    { clue: 'Korean traditional swing', answer: '그네', hint: '줄에 매달아 타는 놀이' },
    { clue: 'Korean traditional seesaw', answer: '널뛰기', hint: '판자 위에서 뛰는 놀이' },
  ],
};
